### ISSUE TITLE
添加重复key判断错误

### ISSUE THREAD

**Issue by zhangchaoza** [liuzhenyulive/DictionaryMini#1]
[https://github.com/liuzhenyulive/DictionaryMini/blob/master/DictionaryMini/DictionaryMini/DictionaryMini.cs#L156](https://github.com/liuzhenyulive/DictionaryMini/blob/master/DictionaryMini/DictionaryMini/DictionaryMini.cs#L156)
添加重复key时，没有抛出异常，原因应该是此处for终止条件错误，应为` i >= 0`，测试后添加重复可以抛出异常

**测试代码：**
> var dicMini = new DictionaryMini<int, string>(5);
> dicMini.Add(1, "old value");
> 
> try
> {
>     dicMini.Add(1, "new value");
> }
> catch (Exception ex)
> {
>     Console.WriteLine(ex.Message);
> }
> 
> Console.WriteLine(dicMini[1]);
> 
> dicMini[1] = "modify value";
> Console.WriteLine(dicMini[1]);

**输出**

> 给定的关键字已存在!
> old value
> modify value

**Comment by JasonLiuLiuLiuLiu** [comment]
大意了 大意了  谢谢 马上修复
